services:
  db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-authdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth-backend
    restart: unless-stopped
    env_file:
      - .env # Carrega as variáveis do arquivo .env
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@auth-db:5432/${DB_NAME:-authdb}?schema=public
      FRONTEND_URL: http://localhost:5173
      # Adicione as variáveis de ambiente aqui ou no arquivo .env
      JWT_SECRET: 3b6e2b0f1e56cddf2a45e4d890d9f7d8731a7db61f334b6a1c8f2c7e2ef9d431b43d22ac9ad4b9e7f45b7b0e4ef31dcd7e5c8a9f27e8e95d4bca87fd81c1f20e
      TMDB_API_KEY: b81ad1dcac0d5acc730d56954f2db0f2
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    stdin_open: true
    tty: true

volumes:
  postgres_data:
